language: php

sudo: false

php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: false

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - composer clear-cache

install: composer update --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner

notifications:
  email: false
